aiohttp==3.9.1
aiosignal==1.3.1
altair==5.2.0
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
async-timeout==4.0.3
attrs==22.2.0
backcall==0.2.0
backoff==2.2.1
beautifulsoup4==4.11.1
bleach==5.0.1
blinker==1.7.0
cachetools==5.3.2
certifi==2023.11.17
cffi==1.15.1
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
cohere==4.42
colorama==0.4.6
comm==0.1.2
debugpy==1.6.5
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
executing==1.2.0
fastavro==1.9.3
fastjsonschema==2.16.2
Flask==3.0.0
fqdn==1.5.1
frozenlist==1.4.1
gitdb==4.0.11
GitPython==3.1.41
hiredis==2.3.2
html2text==2020.1.16
idna==3.4
importlib-metadata==6.11.0
ipykernel==6.20.1
ipython==8.8.0
ipython-genutils==0.2.0
isoduration==20.11.0
itsdangerous==2.1.2
jedi==0.18.2
Jinja2==3.1.2
jsonpointer==2.3
jsonschema==4.17.3
jupyter-events==0.6.3
jupyter_client==7.4.8
jupyter_core==5.1.3
jupyter_server==2.0.6
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
markdown-it-py==3.0.0
MarkupSafe==2.1.1
matplotlib-inline==0.1.6
mdurl==0.1.2
mistune==2.0.4
multidict==6.0.4
nbclassic==0.4.8
nbclient==0.7.2
nbconvert==7.2.7
nbformat==5.7.3
nest-asyncio==1.5.6
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.24.1
packaging==23.0
pandas==1.5.2
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
pillow==10.2.0
platformdirs==2.6.2
prometheus-client==0.15.0
prompt-toolkit==3.0.36
protobuf==4.25.2
psutil==5.9.4
psycopg2-binary==2.9.9
pure-eval==0.2.2
pyarrow==14.0.2
pycparser==2.21
pydeck==0.8.1b0
Pygments==2.14.0
PyMuPDF==1.23.12
PyMuPDFb==1.23.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.4
pytz==2022.7
pywin32==305
pywinpty==2.0.10
PyYAML==6.0
pyzmq==25.0.0
redis==5.0.1
reportlab==4.0.9
requests==2.31.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.7.0
Send2Trash==1.8.0
six==1.16.0
smmap==5.0.1
sniffio==1.3.0
soupsieve==2.3.2.post1
stack-data==0.6.2
streamlit==1.30.0
streamlit-lottie==0.0.5
tenacity==8.2.3
terminado==0.17.1
tinycss2==1.2.1
toml==0.10.2
toolz==0.12.0
tornado==6.2
traitlets==5.8.1
typing_extensions==4.9.0
tzdata==2023.4
tzlocal==5.2
uri-template==1.2.0
urllib3==2.1.0
validators==0.22.0
watchdog==3.0.0
wcwidth==0.2.5
webcolors==1.12
webencodings==0.5.1
websocket-client==1.4.2
Werkzeug==3.0.1
yarl==1.9.4
zipp==3.17.0
